import crypto from 'crypto';

// ── STATIC CODES (fallback / manual issue) ──
const STATIC_CODES = new Set([
  'CVAP-PRO1-2026', 'CVAP-PRO2-2026', 'CVAP-PRO3-2026',
  'CVAP-PRO4-2026', 'CVAP-PRO5-2026', 'CVAP-PRO6-2026',
  'CVAP-PRO7-2026', 'CVAP-PRO8-2026', 'CVAP-PRO9-2026',
  'CVAP-PRO0-2026',
]);

// ── DYNAMIC CODE VALIDATION ──
// Codes generated by stripe-webhook.js follow format: CVAP-XXXX-XXXX
// We validate them by checking they match our generation pattern
// (4 chars from safe alphabet, no confusables)
function isValidCodeFormat(code) {
  return /^CVAP-[A-HJ-NP-Z2-9]{4}-[A-HJ-NP-Z2-9]{4}$/.test(code);
}

// Simple in-memory rate limiting
const attempts = new Map();
const RATE_LIMIT = 5;
const RATE_WINDOW = 15 * 60 * 1000;

function isRateLimited(ip) {
  const now = Date.now();
  const record = attempts.get(ip) || { count: 0, reset: now + RATE_WINDOW };
  if (now > record.reset) {
    attempts.set(ip, { count: 1, reset: now + RATE_WINDOW });
    return false;
  }
  if (record.count >= RATE_LIMIT) return true;
  record.count++;
  attempts.set(ip, record);
  return false;
}

export default async function handler(req, res) {
  if (req.method === 'OPTIONS') {
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
    res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
    return res.status(200).end();
  }

  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  res.setHeader('Access-Control-Allow-Origin', '*');

  // Rate limiting
  const ip = req.headers['x-forwarded-for']?.split(',')[0]?.trim() || req.socket?.remoteAddress || 'unknown';
  if (isRateLimited(ip)) {
    return res.status(429).json({ valid: false, error: 'Too many attempts. Please wait 15 minutes and try again.' });
  }

  const { code } = req.body;
  if (!code || typeof code !== 'string') {
    return res.status(400).json({ valid: false, error: 'No code provided' });
  }

  const normalised = code.trim().toUpperCase();

  // Check static codes first
  const isStatic = STATIC_CODES.has(normalised);

  // Check dynamic code format (issued by stripe-webhook.js)
  const isDynamic = isValidCodeFormat(normalised);

  if (isStatic || isDynamic) {
    // Issue a signed session token
    const secret = process.env.STRIPE_WEBHOOK_SECRET || 'cvapplied-fallback-secret';
    const payload = `${normalised}:${Date.now()}:pro`;
    const token = crypto.createHmac('sha256', secret).update(payload).digest('hex');
    return res.status(200).json({ valid: true, token: `${Buffer.from(payload).toString('base64')}.${token}` });
  }

  // Delay on failure
  await new Promise(r => setTimeout(r, 500));
  return res.status(200).json({ valid: false, error: 'Invalid code. Please check and try again.' });
}
